theme: just-the-docs

title: Philly
description: Yet another PHP framework.
url: "http://localhost:4000"

permalink: pretty
exclude: ["Gemfile", "Gemfile.lock", "CNAME", ".gitignore"]

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/logo.svg"

# Aux links for the upper right navigation
aux_links:
  "Philly on GitHub":
    - "https://github.com/ricardoboss/philly"

# Color scheme supports "light" (default) and "dark"
color_scheme: philly
