remote_theme: pmarsceill/just-the-docs

title: Philly
description: Yet another PHP framework.
url: "https://philly.ricardoboss.de"

permalink: pretty
exclude: ["Gemfile", "Gemfile.lock", "CNAME", ".gitignore"]

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/logo.svg"

# Enable or disable the site search
search_enabled: true

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Philly on GitHub":
    - "https://github.com/ricardoboss/philly"

# Color scheme supports "light" (default) and "dark"
color_scheme: philly
